abbreviation_dict = {"by mouth":["po"],
                    "drops":["gtt"],
                    "female":["f"],
                    "heart rate":["hr"],
                    "history":["hx"],
                    "male":["m"],
                    "normal saline":["ns"],
                    "oxygen saturation":["o2 sat","o2 sats"],
                    "percutaneous endoscopic gastrostomy tube placment":["peg"],
                    "patient":["pt.","pt", "Pts"],
                    "pro re nata":["prn","prn."], 
                    "previous medical history":["pmhx"],
                    "significant":["sig","sig."],
                    "status post":["s/p"],
                    "diastolic blood pressure":["sbp"],
                    "systolic blood pressure":["sbp"],
                    "tracheostomy":["trach"],
                    "ultrasound":["u/s"],
                    "with":["w/"],
                    "without":["w/o"],
                    "year old":["yo","y/o"],
                    }